sudo: true

language: python

cache: pip

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7    
    - os: linux
      dist: bionic
      python: 3.8

before install:
  - chmod +x ./test/regression/run_cron_test.sh

install:
  - sudo apt-get update
  - sudo apt-get install libglu1-mesa
  - export LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
  - pip install -U pip
  - pip install poetry
  - poetry install 
  - pip freeze
  
  # Show all packages, for debugging

before_script:
  - cd $TRAVIS_BUILD_DIR 
  - echo $TRAVIS_BUILD_DIR
  - export PYTHONPATH=${TRAVIS_BUILD_DIR}:${PYTHONPATH}
  - export NUMBA_CACHE_DIR=${HOME}
  
  # Download file for point-in-polyhedron test
  - wget https://raw.githubusercontent.com/keileg/polyhedron/master/polyhedron.py
  # Rename file
  - mv polyhedron.py robust_point_in_polyhedron.py

script: 
  - python setup.py test
  - sh ./test/regression/run_cron_test.sh

after_success:
  - coveralls
